version: '2'

volumes:
  nvidia_driver_367.57:
    external: true

services:
  nginx:
    image: nginx:alpine
    container_name: gardenminer-nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx:ro
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - local

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    restart: always

  ccminer:
    image: gardenminer/miner
    container_name: gardenminer-ccminer-lux
    ports:
      - "4068:4068"
    environment:
      - ALGO=phi1612
      - MINING_POOL=stratum+tcp://pool.bsod.pw:11518
      - USER_NAME=LUgAi9Gs5fW8MKf1ezyGNJbPRniVywo7hY
      - PASSWORD=
      - API_IP=0.0.0.0
      - API_PORT=4068
    volumes:
      - nvidia_driver_367.57:/usr/local/nvidia:ro
      - /etc/localtime:/etc/localtime:ro

  nvidia-smi:
    image: gardenminer/nvidia-smi
    container_name: gardenminer-nvidia-smi
    ports:
      - "9202:9202"
    volumes:
      - nvidia_driver_367.57:/usr/local/nvidia:ro
  
networks:
  local:
    driver: bridge
